export const CONNECTION_REQUEST = 'CONNECTION_REQUEST'
export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS'
export const CONNECTION_FAILED = 'CONNECTION_FAILED'
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'